spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create

    datasource:
        url: jdbc:mysql://localhost:3306/tododb
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver